import { StyleSheet, Text, View } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#141927",
  },
  boxImageBackground: {
    flex: 4,
  },
  boxInfo: {
    flex: 2,
    backgroundColor: "#394057",
    borderTopLeftRadius: 45,
    borderTopRightRadius: 45,
    alignItems: "center",
  },
  btnShowInfo: {
    width: "25%",
    height: 8,
    backgroundColor: "#12204d",
    borderRadius: 20,
    marginTop: 10,
  },

  icAvatar: {
    height: 80,
    width: 80,
    overflow: "hidden",
    borderRadius: 150 / 2,
    borderWidth: 2,
    borderColor: "#12204d",
    marginTop: 8,
  },
  textTitleName: {
    fontFamily: "Sriracha",
    fontSize: 25,
    color: "#aec3f3",
  },
  textContent: {
    fontFamily: "Sriracha",
    fontSize: 15,
    color: "#121e36",
  },
  containerDetail: {
    flex: 1,
    backgroundColor: "#141927",
  },
  touchableIcBack: {
    width: 35,
    height: 90,
  },
  icBack: {
    width: 20,
    resizeMode: "contain",
    tintColor: "#ffffff",
    marginStart: 10,
  },
  boxInfoDetail: {
    width: "90%",
    backgroundColor: "#394057",
    paddingHorizontal: 15,
    paddingVertical: 15,
    borderRadius: 20,
    alignSelf: "center",
    elevation: 10,
    zIndex: 2,
  },
  childInfo1: {
    flexDirection: "row",
  },
  icAvatarDetail: {
    height: 100,
    width: 100,
    overflow: "hidden",
    borderRadius: 20,
    marginRight: 20,
    elevation: 3,
  },
  textContentDetail: {
    fontFamily: "Sriracha",
    fontSize: 15,
    color: "#ffffff",
  },
  childInfo2: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
    alignItems: "center",
    paddingHorizontal: 8,
  },
  textChildTitle: {
    color: "#aec3f3",
    fontFamily: "SignikaNegative",
  },
  textChildContent: {
    fontFamily: "Sriracha",
    fontSize: 16,
    color: "#ffffff",
    alignSelf: "center",
  },
  boxBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#426ad6",
    paddingHorizontal: 5,
    paddingVertical: 8,
    borderRadius: 8,
    elevation: 5,
  },
  icPlus: {
    width: 25,
    height: 25,
    resizeMode: "cover",
    marginRight: 5,
  },
  textButton: {
    color: "#ffffff",
    fontFamily: "SignikaNegative",
    fontSize: 14,
  },
  boxInfoDetail2: {
    position: "absolute",
    width: "100%",
    height: "100%",
    backgroundColor: "#394057",
    top: 200,
    borderRadius: 30,
    paddingTop: 110,
    paddingHorizontal: 10,
    elevation: 5,
  },
  textTitle2: {
    color: "#ffffff",
    fontSize: 16,
    fontFamily: "Sriracha",
    marginBottom: 10,
  },
  boxScrollView: {
    height: 80,
    marginVertical: 8,
  },
  touchableLogo: {
    height: 70,
    width: 70,
    borderRadius: 150 / 2,
    backgroundColor: "#141927",
    marginRight: 10,
    alignItems: "center",
    justifyContent: "center",
    elevation: 8,
  },
  icLogo: {
    height: 50,
    width: 50,
    resizeMode: "center",
    overflow: "hidden",
  },
  icLogo2: {
    height: 50,
    width: 50,
    resizeMode: "center",
    overflow: "hidden",
    borderRadius: 150 / 2,
  },

  album1: {
    flexDirection: "row",
    justifyContent: "space-between",
    top: 0,
  },
  imgAlbum1: {
    width: "48.5%",
    height: 240,
    resizeMode: "center",
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    elevation: 10,
  },
  childAlbum: {
    width: "48.5%",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  imgAlbum2: {
    width: "100%",
    height: 115,
    resizeMode: "contain",
    borderTopRightRadius: 10,
    elevation: 10,
  },
  imgAlbum3: {
    width: "100%",
    height: 115,
    resizeMode: "cover",
    borderBottomRightRadius: 10,
    elevation: 10,
  },
});
